#!/bin/bash -x

PDIR="/ma/porn/xtube"
DL_CMD="youtube-dl --playlist-reverse --continue \
  --write-info-json --write-description \
  -o ${PDIR}/%(uploader)s/%(autonumber)s_%(id)s_%(title)s.%(ext)s"

cd "${PDIR}"

if [ "x$1" = "x" ]; then
  SOURCES=`ls`
else
  SOURCES="$@"
fi

for src in $SOURCES; do
  if [ `echo $src | cut -c 1-4` = "http" ]; then
    url="${src}"
  else
    url="http://www.xtube.com/community/profile.php?user=${src}"
  fi
  ${DL_CMD} "${url}"
done
