#!/bin/bash -x

TARGET_DIR=${1:-"."}
CA_URL="https://support.comodo.com/index.php?/Knowledgebase/Article/GetAttachment/943/30"
CA_FILE="${HOME}/.seedstuff_ca.crt"

if ! type -p wget >/dev/null; then
  echo "ERROR: Need wget.  Please install" >&2
  exit 1
fi

if [ ! -r "${CA_FILE}" ]; then
  wget -O "${CA_FILE}" "${CA_URL}"
fi

cd "${TARGET_DIR}"

for SEEDBOX in `grep "machine .*\.seedstuff\.ca" "$HOME/.netrc" | \
    sed -e 's/^ *//' | cut -f 2 -d \  `; do
  USER=`grep -A 2 "machine ${SEEDBOX}" "$HOME/.netrc" | \
      sed -e 's/^ *//' | grep login | cut -f 2 -d \  `

  if [ ! -d "${TARGET_DIR}" ]; then
    echo "ERROR: No such directory: ${TARGET_DIR}" >&2
    exit 1
  fi

  wget --accept-regex "/$USER/" --ca-certificate="${CA_FILE}" \
    -m https://${SEEDBOX}/${USER}/

  # clean up the silly index files
  find "${SEEDBOX}" -name index.html* -print0 | \
    xargs -0 rm
fi
