#!/usr/bin/python

import urllib
import fileinput
import sys
import base64

def cmd_arg ():
    print base64.b64decode(urllib.unquote(sys.argv[1]))
    return

def read_stdin ():
    running = ""
    for line in fileinput.input():
        running += line
    unurlencoded = urllib.unquote(running)
    try:
        print base64.b64decode(unurlencoded)
    except TypeError:
        try:
            print base64.b64decode(unurlencoded + "=")
        except TypeError:
            print base64.b64decode(unurlencoded + "==")
    return

modes = {'arg' : cmd_arg,
         'stdin' : read_stdin,
         }

mode = 'arg'
try:
    sys.argv[1]
except IndexError:
    mode = 'stdin'

modes[mode]()
