#!/usr/bin/python

import urllib
import fileinput
import sys
import base64

def cmd_arg ():
    print urllib.quote(base64.b64encode(sys.argv[1]))
    return

def read_stdin ():
    running = ""
    for line in fileinput.input():
        running += line
    print urllib.quote(base64.b64encode(running))
    return

modes = {'arg' : cmd_arg,
         'stdin' : read_stdin,
         }

mode = 'arg'
try:
    sys.argv[1]
except IndexError:
    mode = 'stdin'

modes[mode]()
