#!/bin/bash

export NOROOT=1
# shellcheck source=../gen/setup_hdr
source "$(dirname "$0")/../gen/setup_hdr"

if [ ! -r dotbashrc ]; then
  echo "ERROR: can't find stuff"
  exit 1
fi

${INST} dotbashrc "${HOME}/.bashrc"
${INST} dotbash_profile "${HOME}/.bash_profile"
${INST} dotbash_logout "${HOME}/.bash_logout"
${INST} dotscreenrc "${HOME}/.screenrc"
${INST} dottmuxdotconf "${HOME}/.tmux.conf"
${INST} dotalias "${HOME}/.alias"
${INST} dotrubocop.yml "${HOME}/.rubocop.yml"

if [ -r /etc/debian_version ]; then
  ${INST} dotinputrc "${HOME}/.inputrc"
fi
