#!/bin/bash
# $Id$

if [ $EUID != "0" ]; then
    echo "ERROR: must be run as root"
    exit 1
fi

PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin
VOLS=`vos listvldb -localauth | grep '^[a-z]' | grep -v '^u\.'`

for vol in "${VOLS}"; do
    vos rel "$vol" -localauth
done

exit 0
