#!/bin/bash
# $Id$

PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin
VOLS=`vos listvldb -localauth | grep '^u\.'`
vos backupsys -prefix u. -localauth >/dev/null 2>&1

for vol in $VOLS; do
  vos rel "$vol" -localauth >/dev/null >/dev/null 2>&1
done

exit 0
