#!/bin/bash
# $Id$

if [ $EUID != "0" ]; then
    echo "ERROR: must be run as root"
    exit 1
fi

PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin
VOLS=`vos listvldb -localauth | grep '^[a-tv-z]'`

for vol in ${VOLS}; do
    echo "releasing $vol";
    vos rel "$vol" -localauth 2>&1
done

exit 0
