#!/bin/bash

SYS_IFS="${IFS}"
LF_IFS="
"
IFS="${LF_IFS}"

TARGET_RW_SERVER="amber.tursom.org"
TARGET_RW_PART="a"
TARGET_RO_SERVER="steam.tursom.org"
TARGET_RO_PART="a"

VOL=$1

if [ -z "${VOL}" ]; then
    echo "plz specify a volume; bail"
    exit 1
fi

VOS=/usr/sbin/vos
if [ ! -x "${VOS}" ]; then
    echo "${VOS} isn't there; bail" >&2
    exit 1
fi

if ! klist -t; then
    echo "no tickets; bail" >&2
    exit 1
fi

ADMIN_PRINC=`klist | grep Principal: | grep /admin@`
if [ -z "${ADMIN_PRINC}" ]; then
    echo "need an admin principal; bail" >&2
    exit 1
fi

LOCS=`/usr/sbin/vos examine "${VOL}" 2>/dev/null| grep 'Site\ *$' | sed -e 's/^\ *//gm' | cut -f 2,4,5 -d ' ' | sed -e 's,/vicep,,'`

if [ -z "${LOCS}" ]; then
    echo "${VOL} not found: $LOCS" >&2
    exit 1
fi

RO_LOCS=`echo "${LOCS}" | grep 'RO$' | sed -e 's/ RO//gm'`

if [ -z "${RO_LOCS}" ]; then
    echo "${VOL} has no readonly sites; bail" >&2
    exit 1
fi

RW_LOC_SERVER=`echo "${LOCS}" | grep 'RW$' | awk '{print $1}'`
RW_LOC_PART=`echo "${LOCS}" | grep 'RW$' | awk '{print $2}' | sed -e 's,/vicep,,'`

if [ -z "${RW_LOC_SERVER}" ] || [ -z  "${RW_LOC_PART}" ]; then
    echo "${VOL} has no master site, wtf?; bail" >&2
    exit 1
fi

if [ "${RW_LOC_SERVER}" == "${TARGET_RW_SERVER}" ] && \
    [ "${RW_LOC_PART}" == "${TARGET_RW_PART}" ]; then
    echo "${VOL} master already lives on ${TARGET_RW_PART}; bail" >&2
    exit 1
fi

for old_ro_loc in ${RO_LOCS}; do
    export IFS="${SYS_IFS}"
    ${VOS} remove $old_ro_loc -id "${VOL}.readonly"
    export IFS="${LF_IFS}"
done

${VOS} addsite -server ${TARGET_RW_SERVER} \
    -partition ${TARGET_RW_PART}  -id "${VOL}"
${VOS} addsite -server ${TARGET_RO_SERVER} \
    -partition ${TARGET_RO_PART} -id "${VOL}"

${VOS} move -id "${VOL}" \
    -fromserver "${RW_LOC_SERVER}" -frompartition "${RW_LOC_PART}" \
    -toserver "${TARGET_RW_SERVER}" -topartition "${TARGET_RW_PART}"
${VOS} release -id "${VOL}"

exit 0
