#!/bin/bash
# $Id: setup 13 2009-08-02 23:21:57Z tmaher $

. `dirname "$0"`/../gen/setup_hdr

if [ ! -r update_demonoid ]; then
  echo "ERROR: can't find stuff"
  exit 1
fi

${INST_N} update_demonoid /usr/local/bin/

