#!/usr/local/bin/bash
# $Id$

PATH=$PATH:/usr/local/bin:/usr/local/sbin
export PATH

let SLEEPTIME="($RANDOM -367) % 3600"
sleep $SLEEPTIME

umask 077
CK_SAVE="/var/tmp/ttcookie"
if [ ! -d ${CK_SAVE} ]; then
  mkdir ${CK_SAVE}
fi
if [ ! -d ${CK_SAVE} ]; then
  echo "NO TMP DIR ${CK_SAVE}, OMG!"
  exit 1
fi

CK=`mktemp /var/tmp/ttcookie/cookie.XXXXXX` || exit 1

POST=$HOME/private/tvtorrents.post
WGET="wget -q --load-cookies $CK --keep-session-cookies --save-cookies $CK"

rm -f ${CK_SAVE}/log[123]

$WGET -O ${CK_SAVE}/log1 "http://www.tvtorrents.com/"
$WGET --post-file $POST -O ${CK_SAVE}/log2 \
  "http://www.tvtorrents.com/login.do"
$WGET -O ${CK_SAVE}/log3 "http://www.tvtorrents.com/loggedin/my/fav_shows.do"

exit 0
