#!/usr/local/bin/bash
# $Id$

PATH=$PATH:/usr/local/bin:/usr/local/sbin
export PATH

let SLEEPTIME="($RANDOM -367) % 3600"
sleep $SLEEPTIME

UA='Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.5; en-US; rv:1.9.1.5) Gecko/20091102 Firefox/3.5.5'

umask 077
CK_SAVE="/var/tmp/ttcookie"
if [ ! -d ${CK_SAVE} ]; then
  mkdir ${CK_SAVE}
fi
if [ ! -d ${CK_SAVE} ]; then
  echo "NO TMP DIR ${CK_SAVE}, OMG!"
  exit 1
fi

CK=`mktemp /var/tmp/ttcookie/cookie.XXXXXX` || exit 1

POST=$HOME/private/tvtorrents.post
CURL="curl -b $CK -c $CK"
# WGET="wget -q --load-cookies $CK --keep-session-cookies --save-cookies $CK"

rm -f ${CK_SAVE}/log[123]

$CURL -A "$UA" -o ${CK_SAVE}/log1 "http://www.tvtorrents.com/"
$CURL -A "$UA" -o ${CK_SAVE}/log2 -d @${POST} "http://tvtorrents.com/login.do"
$CURL -A "$UA" -o ${CK_SAVE}/log3 "http://www.tvtorrents.com/loggedin/my/fav_shows.do"

exit 0
