#!/usr/bin/env ruby
ENV['PATH'] += ":#{File.dirname __FILE__}"

require 'open3'

CHAPTER_FILE = "chapters.txt"
BOOK_FILE = "_book.m4b"
TMP_FILE = "_tmp.m4b"

chapters = ARGV.reduce(Array.new) {|files, path| files | Dir.glob(path) }
raise "\nneed one or more files" if chapters.first.nil?
chapters.sort!

cmd_arr = ARGV
cmd_arr.unshift "mkchapterfile"
o,e,s = Open3.capture3 cmd_arr
raise "\ncould not figure out chapters\n#{e}" unless s.success?
File.open("chapters.txt", "w") { |f| f.write o }

FileUtils.copy chapters.shift, BOOK_FILE
chapters.each_slice(10) do |files|
  cmd_arr = ['MP4Box', '-flat', '-cat', BOOK_FILE]
  files.each { |chapter| cmd_arr.push "-cat", chapter }
  cmd_arr.push TMP_FILE
  o,e,s = Open3.capture3 cmd_arr
  raise "\ncould not merge files\n#{e}" unless s.success?
  puts o
  FileUtils.mv TMP_FILE, BOOK_FILE
end

o,e,s = Open3.capture3 ['MP4Box', '-chap', CHAPTER_FILE, BOOK_FILE]
raise "\ncould not merge chapters\n#{e}" unless s.success?
puts o
puts "*"*20
puts "DONE"
