#!/bin/bash
# $Id$

. `dirname "$0"`/../gen/setup_hdr

if [ ! -r "${DIR}/homebot.xml" ]; then
  echo "ERROR: can't find stuff"
  exit 1
fi

${INST_N} homebot.xml /home/homebot/conf/
${INST_N} youtube_talk /usr/local/libexec

../gen/setup

/sbin/service youtube_talk restart
