#!/bin/bash
# $Id$

INST="/usr/bin/install"
INST_N="${INST} -o root -g root -D"

if [ $EUID != "0" ]; then
  echo "ERROR: must run as root/sudo"
  exit 1
fi

DIR=`dirname "$0"`
cd "$DIR"

if [ ! -r "${DIR}/homebot.xml" ]; then
  echo "ERROR: can't find stuff"
  exit 1
fi

${INST_N} homebot.xml /home/homebot/conf/
${INST_N} youtube_talk /usr/local/libexec/
