#!/bin/bash
# $Id$

. `dirname "$0"`/../gen/setup_hdr

if [ ! -r dhcpd.master ]; then
  echo "ERROR: can't find stuff"
  exit 1
fi

. /etc/sysconfig/network
SHORTHOST=`echo $HOSTNAME | cut -f 1 -d \. `

if [ ! -d /etc/dhcp ]; then
    mkdir /etc/dhcp
fi
${INST_RO} dhcpd.master /etc/dhcp/
${INST_RO} dhcpd.conf.${SHORTHOST} /etc/dhcp/dhcpd.conf
if [ ! -L /etc/dhcpd.conf ]; then
    if [ -r /etc/dhcpd.conf ]; then rm -f /etc/dhcpd.conf; fi
    ln -s /etc/dhcp/dhcpd.conf /etc/dhcpd.conf
fi
if [ -r /etc/dhcpd.master ]; then
    rm -f /etc/dhcpd.master
fi
