#!/bin/bash
# $Id$
#
# mt-daapd: iTunes audio server
#
# chkconfig: - 99 1
# description: daap (iTunes) audio server
# processname: mt-daapd
# config: /etc/mt-daapd.conf
#
### BEGIN INIT INFO
# Provides: mt-daapd
# Required-Start: $syslog
# Default-Stop: 0 1 6
# Short-Description: daap (iTunes) audio server
# Description: daap (iTunes) audio server, aka, Firefly Media Server
### END INIT INFO

EXECFILE=/opt/mt-daapd/sbin/mt-daapd

# Sanity checks.
[ -x $EXECFILE ] || exit 0

# Source function library.
. /etc/init.d/functions

RETVAL=0
prog=mt-daapd

PIDF=/var/run/mt-daapd.pid

start () {
  if [ -f $PIDF  ]; then
	PID=`cat $PIDF`
	if [ `ps -p $PID|wc -l` -gt 1 ]; then
		echo "$0: $PIDF exists and processs seems to be running. Exiting."
		exit 1;
	fi;
  fi;

  echo -n $"Starting $prog: "
  daemon $EXECFILE
  RETVAL=$?
  echo
  return $RETVAL
}

stop () {
  echo -n $"Stopping $prog: "
  if [ ! -r $PIDF ]; then
    echo "can't find pidfile"
    return 1
  fi
  PYPID=`cat $PIDF`
  if [ "x$PYPID" == "x" ]; then
    echo "can't determine pid!"
    return 1
  fi
  kill $PYPID
  RETVAL=$?
  if [ $RETVAL -eq 0 ]; then
    success $"$prog shutdown"
  else
    failure $"$prog shutdown"
  fi
  echo ""
  if [ -f $PIDF ]; then rm $PIDF; fi
  return $RETVAL
}

restart () {
  stop
  start
}

case "$1" in
  start)
    start
    RETVAL=$?
  ;;
  stop)
    stop
    RETVAL=$?
  ;;
  restart)
    restart
    RETVAL=$?
  ;;
  *)
    echo $"Usage: $0 {start|stop|restart}"
    RETVAL=1
  ;;
esac
exit $RETVAL
