#!/bin/bash
# $Id$
#
# youtube_talk: homebot!
#
# chkconfig: - 99 1
# description: talk to youtube
# processname: perl
# config: /home/homebot/conf/homebot.xml
#
### BEGIN INIT INFO
# Provides: youtube_talk
# Required-Start: $syslog
# Default-Stop: 0 1 6
# Short-Description: talk to youtube
# Description: talk to youtube; sometimes it talks back
### END INIT INFO

EXECFILE=/usr/local/libexec/youtube_talk

# Sanity checks.
[ -x $EXECFILE ] || exit 0

# Source function library.
. /etc/init.d/functions

RETVAL=0
prog="tursom.org Homebot"

PIDF=/var/run/homebot/pid

start () {
  if [ -f $PIDF  ]; then
	PID=`cat $PIDF`
	if [ `ps -p $PID|wc -l` -gt 1 ]; then
		echo "$0: $PIDF exists and processs seems to be running. Exiting."
		exit 1;
	fi;
  fi;

  echo -n $"Starting $prog: "
  daemon $EXECFILE
  RETVAL=$?
  echo
  return $RETVAL
}

stop () {
  echo -n $"Stopping $prog: "
  if [ ! -r $PIDF ]; then
    echo "can't find pidfile"
    return 1
  fi
  PYPID=`cat $PIDF`
  if [ "x$PYPID" == "x" ]; then
    echo "can't determine pid!"
    return 1
  fi
  kill $PYPID
  RETVAL=$?
  if [ $RETVAL -eq 0 ]; then
    success $"$prog shutdown"
  else
    failure $"$prog shutdown"
  fi
  echo ""
  if [ -f $PIDF ]; then rm $PIDF; fi
  return $RETVAL
}

restart () {
  stop
  start
}

case "$1" in
  start)
    start
    RETVAL=$?
  ;;
  stop)
    stop
    RETVAL=$?
  ;;
  restart)
    restart
    RETVAL=$?
  ;;
  *)
    echo $"Usage: $0 {start|stop|restart}"
    RETVAL=1
  ;;
esac
exit $RETVAL
