#!/usr/bin/env ruby

require 'timeout'
require 'socket'

UDP_MAXLEN = 2**16
UDPSocket.do_not_reverse_lookup = true  # don't do an extra DNS lookup

# http://www.upnp.org/specs/arch/UPnP-arch-DeviceArchitecture-v1.1.pdf
# see section 1.3.2 - "Search request with M-SEARCH"
disco_addr = "239.255.255.250"
disco_port = 1900
payload = <<__EOS
M-SEARCH * HTTP/1.1
HOST: #{disco_addr}:#{disco_port}
MAN: "ssdp:discover"
MX: 2
ST: upnp:rootdevice

__EOS

u = UDPSocket.new
u.send payload, 0, disco_addr, disco_port

begin
  timeout(5) do
    while true do
      id = u.recvfrom(UDP_MAXLEN)
      puts "\n** NEW **\n#{u.recvfrom(UDP_MAXLEN)[0]}"
    end
  end
rescue
  puts "done"
end
