#!/bin/bash
# $Id$

. `dirname "$0"`/../gen/setup_hdr

if [ ! -r named.conf ]; then
  echo "ERROR: can't find stuff"
  exit 1
fi

. /etc/sysconfig/network
SHORTHOST=`echo $HOSTNAME | cut -f 1 -d \. `

${INST_RO} resolv.conf.${SHORTHOST} /etc/resolv.conf

${INST_RO} named.conf /etc/
${INST_RO} named.conf /var/named/chroot/etc/

${INST_RO} named.root /etc/
${INST_RO} named.root /var/named/chroot/var/named/

${INST_RO} db.127.0.0 /var/named/chroot/var/named/
${INST_RO} db.192.168.123 /var/named/chroot/var/named/
