#!/bin/bash
# $Id$

. `dirname "$0"`/../gen/setup_hdr

if [ ! -r named.conf ]; then
  echo "ERROR: can't find stuff"
  exit 1
fi

SHORTHOST=`hostname | cut -f 1 -d \. `

if [ ! -d /var/log/named ]; then
  mkdir -p /var/log/named
  chown bind:bind /var/log/named
fi

${INST_RO} resolv.conf.${SHORTHOST} /etc/resolv.conf

${INST_RO} named.conf /etc/bind/

${INST_RO} named.root /var/lib/bind/
${INST_RO} db.127.0.0 /var/lib/bind/
${INST_RO} db.192.168.123 /var/lib/bind/
