#!/bin/bash
# $Id$

. `dirname "$0"`/../gen/setup_hdr

for ACCT in tmaher homebot transmission root; do
    CTAB="${ACCT}.${HOST_SHORT}" export CTAB
    if [ ! -r "${CTAB}" ]; then
        CTAB="${ACCT}" export CTAB
    fi
    if [ ! -r "${CTAB}" ]; then
        continue
    fi

    crontab -u "${ACCT}" "${CTAB}"
done
